FROM python:3.7.7-slim-buster

RUN apt-get update && apt-get -y install \
      	sudo \
      	wireless-tools \
    && apt-get -y autoremove \
    && apt-get clean autoclean

COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt --ignore-installed

COPY . /app/

CMD ["python3", "/app/navigation.py", "/app/configs/config.yaml"]
